job:
  - name: Backup1
    template_path: /opt/airflow/template/job2.template
    dag_output_locate: /opt/airflow/dags/
  - name: Backup2
    template_path: /opt/airflow/template/job2.template
    dag_output_locate: /opt/airflow/dags/